import = ["~/.config/alacritty/themes/themes/gruvbox_dark.toml"]


[font]
size = 18

[font.normal]
family = "UbuntuMono Nerd Font"

[window]
decorations = "none"
opacity =  1
decorations_theme_variant = "dark"

[window.padding]
x = 0
y = 0

[mouse]
hide_when_typing = true
